import "./globals.css";
import CommonLayout from "@/src/layout/Common";

export const metadata = {
  // title: "Conscious Namaz",
  // description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Set the favicon path
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`pt-[--header-height] antialiased`}
      >
        <CommonLayout>{children}</CommonLayout>
      </body>
    </html>
  );
}
